---
title: "TreeBuilding"
author: "Vinny Chloros"
format: html
editor: visual
---

```{r setup}
library(ape)
library(phangorn)
library(BiocManager)
#library(fastreeR)
#library(utils)
#library(stats)
#library(grid)
#library(BiocFileCache)
#BiocManager::install("ggtree")
library(ggtree)
library(ggplot2)
library(patchwork)
library(tictoc)

set.seed(17032025)
```

# Phangorn Tree

```{r }
felidae <- read.phyDat("FelidaeAlignedNames.fas", format = "fasta")
```

```{r run model}
#elapsed time: 11 secs

#| message: false
tictoc::tic()
fitGTR <- pml_bb(felidae, model="GTR+G(4)+I", rearrangement = "NNI", method = "ultrametric")
tictoc::toc()
```

```{r}
plotBS(midpoint(fitGTR$tree), p = .5, type="p", digits=2, main="Ultrafast bootstrap")
```

```{r}
ggtree(fitGTR$tree, branch.length="none") +
  geom_tiplab(size = 3, color = "purple") +
  xlim(c(0, 50))
```

```{r bootstrapping}
#elapsed time: ~10 minutes

tictoc::tic()
bs <- bootstrap.pml(fitGTR, bs=100, optNni=TRUE,
    control = pml.control(trace = 0), jumble = TRUE)
tictoc::toc()
```


```{r visualizing}
plotBS(midpoint(fitGTR$tree), bs, p = 50, type="p", main="Standard bootstrap")

tree_stdbs <- plotBS(fitGTR$tree, bs, type = "p")

ggtree(tree_stdbs, branch.length="none") +
  geom_tiplab(size = 3, color = "purple") +
  xlim(c(0, 50))

plot.phylo(tree_stdbs, use.edge.length = FALSE)

```


```{r check bootstrapping}
#| eval: false

ggtree(bs, branch.length = "none") + 
  facet_wrap( ~.id, scale="free") + 
  theme_tree2()
```

```{r export tree}
png('RFelidaeTree.png')
plot.phylo(tree_stdbs, use.edge.length = FALSE)
dev.off()
```
